create table
  public.products (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text null,
    price numeric not null,
    constraint products_pkey primary key (id)
  );

alter table public.products enable row level security;

create policy "Products are viewable by everyone." on public.products for select using (true);
create policy "Users can insert their own products." on public.products for insert with check (auth.uid() = owner_id); -- Assuming you add an owner_id column